language: node_js
node_js:
  - '10'
  - '12'
  - '14'
env:
  - CUMCUMBER_VERSION=4.x
  - CUMCUMBER_VERSION=5.x
  - CUMCUMBER_VERSION=6.x
script:
  - yarn add cucumber@${CUMCUMBER_VERSION}
  - yarn run lint
  - yarn run check-fmt
  - yarn run test-cover
  - yarn run examples -- --tags @offline
after_success:
  - yarn run coverage
